#!/usr/bin/env bash
set -euo pipefail
set +H

cd /Users/chetantemkar/development/alphaarena

pkill -f quantplot_ai_server.py || true

ALPHA_INSECURE_SSL=1 \
ALPHA_LIVE_TRADING=0 \
ALPHA_PAPER_MODE=1 \
ALPHA_AUTO_SELECT_ENABLED=0 \
ALPHA_SIGNAL_STRATEGY=simple_prompt \
ALPHA_CANARY_ENABLED=0 \
ALPHA_BASE_SIGNAL_CHANCE=1.0 \
ALPHA_MIN_PROFIT_EDGE_PCT=0.03 \
ALPHA_MIN_PROFIT_EDGE_PCT_BTC=0.05 \
ALPHA_MIN_PROFIT_EDGE_PCT_BASKET=0.06 \
ALPHA_MIN_TRADE_MOVE_PCT=0.0 \
ALPHA_MOMENTUM_OVERRIDE_THRESHOLD_PCT=0.03 \
ALPHA_MOMENTUM_OVERRIDE_THRESHOLD_PCT_BTC=0.04 \
ALPHA_MOMENTUM_OVERRIDE_THRESHOLD_PCT_BASKET=0.06 \
ALPHA_DIRECTIONAL_PERSISTENCE_MIN_STREAK_BASKET=2 \
ALPHA_REVERSAL_EDGE_MULTIPLIER_BASKET=1.5 \
ALPHA_BASKET_ORDER_USD=30 \
ALPHA_HOLD_STREAK_MOMENTUM_OVERRIDE_ENABLED=0 \
ALPHA_PAPER_FORCE_CLOSE_ON_HOLD=0 \
ALPHA_DISABLE_BASKET_TIMEOUT_FALLBACK=1 \
ALPHA_PAPER_RISK_OFF_MAX_DRAWDOWN_PCT=0.20 \
python3 quantplot_ai_server.py >/tmp/alpha_profit_server.log 2>&1 &
SERVER_PID=$!

cleanup() {
  kill "$SERVER_PID" >/dev/null 2>&1 || true
  wait "$SERVER_PID" >/dev/null 2>&1 || true
}
trap cleanup EXIT

sleep 4

ALPHA_CONTROLLED_DURATION_SECONDS=1800 \
ALPHA_CONTROLLED_POLL_SECONDS=15 \
ALPHA_CONTROLLED_ENABLE_BTC=0 \
ALPHA_CONTROLLED_ENABLE_BASKET=1 \
ALPHA_CONTROLLED_BASKET_MODEL=Llama-3.2 \
python3 run_controlled_paper_session.py | tee /tmp/alpha_profit_run.log
